// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFZzUK23Rf76bcZLw6u85lMD0SqPLqCc',
    appId: '1:624619623676:web:0b5fd06c768bad5a1ef379',
    messagingSenderId: '624619623676',
    projectId: 'genome-fe61e',
    authDomain: 'genome-fe61e.firebaseapp.com',
    storageBucket: 'genome-fe61e.firebasestorage.app',
    measurementId: 'G-66WPWLB895',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVZiCZnroYK4n7fTbT-XlBkdcBt4j0Vs',
    appId: '1:624619623676:android:78f1280728d882f41ef379',
    messagingSenderId: '624619623676',
    projectId: 'genome-fe61e',
    storageBucket: 'genome-fe61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPzJ485VSyJdrLqa8zZ7UA9PNFJLwD5E0',
    appId: '1:624619623676:ios:3bef1c2fe3fead6d1ef379',
    messagingSenderId: '624619623676',
    projectId: 'genome-fe61e',
    storageBucket: 'genome-fe61e.firebasestorage.app',
    iosBundleId: 'com.example.genome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPzJ485VSyJdrLqa8zZ7UA9PNFJLwD5E0',
    appId: '1:624619623676:ios:3bef1c2fe3fead6d1ef379',
    messagingSenderId: '624619623676',
    projectId: 'genome-fe61e',
    storageBucket: 'genome-fe61e.firebasestorage.app',
    iosBundleId: 'com.example.genome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALFZzUK23Rf76bcZLw6u85lMD0SqPLqCc',
    appId: '1:624619623676:web:c28fc023d01725151ef379',
    messagingSenderId: '624619623676',
    projectId: 'genome-fe61e',
    authDomain: 'genome-fe61e.firebaseapp.com',
    storageBucket: 'genome-fe61e.firebasestorage.app',
    measurementId: 'G-FCD9285ZH9',
  );
}
